// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package subsystems;

import edu.wpi.first.wpilibj.motorcontrol.PWMVictorSPX;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.Constants;
import frc.robot.commands.Intake_Ball;

public class Intake extends SubsystemBase {
  public final PWMVictorSPX Intake;
  /** Creates a new Climber. */
  public Intake() {
  Intake = new PWMVictorSPX(Constants.INTAKE_MOTOR);
  Intake.setInverted(false);
  }

  public void initDefaultCommand() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // Set the default command for a subsystem here.
    setDefaultCommand(new Intake_Ball(.5));
}

  @Override
  public void periodic() {
    // This method will be called once per scheduler run
  }


  public void intakeBall(double speed)
  {
    Intake.set(speed);
  }

}
